name: Run Backend App

on:
  schedule:
    - cron: "0 * * * *" # Exécute toutes les heures

jobs:
  run-app:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
      
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Installer les dépendances
        run: npm install
      
      - name: Exécuter le backend
        run: node index.js
