name: Mise à jour des données

on:
  push:
    paths:
      - "data.json"

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Mise à jour des données
        run: |
          echo '{}' > data.json
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Mise à jour automatique des données"
          git push
